# -*- coding: utf-8 -*-
"""Actividad_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bITw40WcnX7BhreV5FPYtLzVtlaJRri5
"""

!pip install xlrd
!pip install openpyxl

# Importamos librerias
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from pandas.plotting import scatter_matrix

# Leemos el archivo excel
serie = pd.read_excel(io = "Base.xlsx", sheet_name="hoja")
# Se pone el campo fecha como un indice
serie['FECHA_CORTE']=pd.to_datetime(serie['FECHA_CORTE'])
df=serie.set_index('FECHA_CORTE')
#Observamos los datos con los que se cuenta
df

# Visualización del comportamiento de los fondos.
from matplotlib import pyplot
figsize=(10,5)
df.plot()
plt.title('Tendencia de fondos', fontsize=15)
plt.xlabel('Fecha', fontsize=10)
plt.ylabel('Afiliados en millones decimales', fontsize=10)
plt.show()

# Se hace los boxplot
plt.figure(figsize=(10, 5))
sns.boxplot(data=df, orient="h", fliersize=10)
plt.title('Comportamiento de fondos', fontsize=15)
plt.xlabel('Afiliados en millones decimales', fontsize=10)
plt.show()

#Creamos la tabla que describe el comportamiento de los datos
df.describe()